// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1jnEqzpmPJ4oZXFu8ZbcSY33KqNH4D4',
    appId: '1:743301996065:web:1ed87a541ed219a9b0cd60',
    messagingSenderId: '743301996065',
    projectId: 'braillerecognitionapp',
    authDomain: 'braillerecognitionapp.firebaseapp.com',
    storageBucket: 'braillerecognitionapp.firebasestorage.app',
    measurementId: 'G-0XGDTERN51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmityjbViI6l1zhvS78LYgJjJzu60Pjy8',
    appId: '1:743301996065:android:36abd735af7e1727b0cd60',
    messagingSenderId: '743301996065',
    projectId: 'braillerecognitionapp',
    storageBucket: 'braillerecognitionapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnH3tJLT4cdOoyWBaYKhl3ieYCA7wJito',
    appId: '1:743301996065:ios:06e52c8075d374a0b0cd60',
    messagingSenderId: '743301996065',
    projectId: 'braillerecognitionapp',
    storageBucket: 'braillerecognitionapp.firebasestorage.app',
    iosBundleId: 'uz.mq.braillerecognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnH3tJLT4cdOoyWBaYKhl3ieYCA7wJito',
    appId: '1:743301996065:ios:44a03163c4a5942bb0cd60',
    messagingSenderId: '743301996065',
    projectId: 'braillerecognitionapp',
    storageBucket: 'braillerecognitionapp.firebasestorage.app',
    iosBundleId: 'com.example.braillerecognition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW1jnEqzpmPJ4oZXFu8ZbcSY33KqNH4D4',
    appId: '1:743301996065:web:55b81bc83a10c2bfb0cd60',
    messagingSenderId: '743301996065',
    projectId: 'braillerecognitionapp',
    authDomain: 'braillerecognitionapp.firebaseapp.com',
    storageBucket: 'braillerecognitionapp.firebasestorage.app',
    measurementId: 'G-W4LZ77BKKN',
  );
}
